
import { Building, Research, Ship } from './types';

export const GAME_CONFIG = {
  points_per_resource: 0.001,
  debris_ratio: 0.3,
  repair_chance: 0.7,
  combat_rounds: 6,
  moon_max_chance: 0.20,
};

export const BUILDINGS: Record<string, Building> = {
  metal_mine: {
    id: 'metal_mine',
    name: 'Metal Mine',
    description: 'Extracts metal ores from the planetary crust.',
    baseCost: { metal: 60, crystal: 15 },
    multiplier: 1.5,
    productionFormula: (L) => 30 * L * Math.pow(1.1, L),
    energyConsumption: (L) => 10 * L * Math.pow(1.1, L),
  },
  crystal_mine: {
    id: 'crystal_mine',
    name: 'Crystal Mine',
    description: 'Harvests silicon and rare earth crystals.',
    baseCost: { metal: 48, crystal: 24 },
    multiplier: 1.5,
    productionFormula: (L) => 20 * L * Math.pow(1.1, L),
    energyConsumption: (L) => 10 * L * Math.pow(1.1, L),
  },
  deut_synthesizer: {
    id: 'deut_synthesizer',
    name: 'Deuterium Synthesizer',
    description: 'Extracts deuterium from planetary water deposits.',
    baseCost: { metal: 225, crystal: 75 },
    multiplier: 1.5,
    productionFormula: (L) => 10 * L * Math.pow(1.1, L),
    energyConsumption: (L) => 20 * L * Math.pow(1.1, L),
  },
  solar_plant: {
    id: 'solar_plant',
    name: 'Solar Plant',
    description: 'Photo-voltaic cells provide primary energy.',
    baseCost: { metal: 75, crystal: 30 },
    multiplier: 1.5,
    energyProduction: (L) => 20 * L * Math.pow(1.1, L),
  },
  fusion_reactor: {
    id: 'fusion_reactor',
    name: 'Fusion Reactor',
    description: 'Uses deuterium to generate massive power.',
    baseCost: { metal: 900, crystal: 360, deuterium: 180 },
    multiplier: 1.5,
    energyProduction: (L) => 30 * L * Math.pow(1.05, L),
    requirements: { deut_synthesizer: 5, energy_tech: 3 },
  },
  robotics_factory: {
    id: 'robotics_factory',
    name: 'Robotics Factory',
    description: 'Reduces construction time of buildings.',
    baseCost: { metal: 400, crystal: 120, deuterium: 200 },
    multiplier: 1.5,
  },
  shipyard: {
    id: 'shipyard',
    name: 'Shipyard',
    description: 'Facility for constructing naval and defensive units.',
    baseCost: { metal: 400, crystal: 200, deuterium: 100 },
    multiplier: 1.5,
    requirements: { robotics_factory: 2 },
  },
  research_lab: {
    id: 'research_lab',
    name: 'Research Lab',
    description: 'Unlocks advanced technologies and drives.',
    baseCost: { metal: 200, crystal: 400, deuterium: 200 },
    multiplier: 1.5,
  },
  nanite_factory: {
    id: 'nanite_factory',
    name: 'Nanite Factory',
    description: 'Micro-bots that drastically speed up all construction.',
    baseCost: { metal: 20000, crystal: 15000, deuterium: 10000 },
    multiplier: 1.5,
    requirements: { robotics_factory: 10, computer_tech: 10 },
  },
  terraformer: {
    id: 'terraformer',
    name: 'Terraformer',
    description: 'Expands usable planetary surface. Adds +5 fields per level.',
    baseCost: { crystal: 50000, deuterium: 100000 },
    multiplier: 1.5,
    requirements: { nanite_factory: 1, energy_tech: 12 },
  },
  missile_silo: {
    id: 'missile_silo',
    name: 'Missile Silo',
    description: 'Stores interplanetary and anti-ballistic missiles.',
    baseCost: { metal: 20000, crystal: 20000, deuterium: 1000 },
    multiplier: 1.5,
    requirements: { shipyard: 1 },
  },
  space_dock: {
    id: 'space_dock',
    name: 'Space Dock',
    description: 'Orbital repair facility for damaged fleets.',
    baseCost: { metal: 200, crystal: 0, deuterium: 50, energy: 50 },
    multiplier: 5.0,
    requirements: { shipyard: 2 },
  },
  metal_storage: {
    id: 'metal_storage',
    name: 'Metal Storage',
    description: 'Increases maximum metal capacity.',
    baseCost: { metal: 1000 },
    multiplier: 1.5,
  },
  crystal_storage: {
    id: 'crystal_storage',
    name: 'Crystal Storage',
    description: 'Increases maximum crystal capacity.',
    baseCost: { metal: 1000, crystal: 500 },
    multiplier: 1.5,
  },
  deut_tank: {
    id: 'deut_tank',
    name: 'Deuterium Tank',
    description: 'Increases maximum deuterium capacity.',
    baseCost: { metal: 1000, crystal: 1000 },
    multiplier: 1.5,
  }
};

export const RESEARCH: Record<string, Research> = {
  energy_tech: {
    id: 'energy_tech',
    name: 'Energy Tech',
    description: 'Foundation for all high-output power systems.',
    baseCost: { crystal: 800, deuterium: 400 },
    multiplier: 2.0,
    requirements: { research_lab: 1 },
  },
  laser_tech: {
    id: 'laser_tech',
    name: 'Laser Tech',
    description: 'Concentrated light research for weapon systems.',
    baseCost: { metal: 200, crystal: 100 },
    multiplier: 2.0,
    requirements: { research_lab: 1, energy_tech: 2 }
  },
  ion_tech: {
    id: 'ion_tech',
    name: 'Ion Tech',
    description: 'Molecular destabilization research.',
    baseCost: { metal: 1000, crystal: 300, deuterium: 100 },
    multiplier: 2.0,
    requirements: { research_lab: 4, energy_tech: 4, laser_tech: 5 }
  },
  hyperspace_tech: {
    id: 'hyperspace_tech',
    name: 'Hyperspace Tech',
    description: 'Dimensional travel theory.',
    baseCost: { crystal: 4000, deuterium: 2000 },
    multiplier: 2.0,
    requirements: { research_lab: 7, energy_tech: 5, shield_tech: 5 }
  },
  plasma_tech: {
    id: 'plasma_tech',
    name: 'Plasma Tech',
    description: 'High-energy state matter research for heavy weaponry.',
    baseCost: { metal: 2000, crystal: 4000, deuterium: 1000 },
    multiplier: 2.0,
    requirements: { research_lab: 4, energy_tech: 8, laser_tech: 10, ion_tech: 5 }
  },
  combustion_drive: {
    id: 'combustion_drive',
    name: 'Combustion Drive',
    description: '+10% Speed per level for basic ships.',
    baseCost: { metal: 400, deuterium: 600 },
    multiplier: 2.0,
    requirements: { research_lab: 1, energy_tech: 1 }
  },
  impulse_drive: {
    id: 'impulse_drive',
    name: 'Impulse Drive',
    description: '+20% Speed per level.',
    baseCost: { metal: 2000, crystal: 4000, deuterium: 600 },
    multiplier: 2.0,
    requirements: { research_lab: 2, energy_tech: 1 }
  },
  hyperspace_drive: {
    id: 'hyperspace_drive',
    name: 'Hyperspace Drive',
    description: '+30% Speed per level.',
    baseCost: { metal: 10000, crystal: 20000, deuterium: 6000 },
    multiplier: 2.0,
    requirements: { research_lab: 7, hyperspace_tech: 3 }
  },
  espionage_tech: {
    id: 'espionage_tech',
    name: 'Espionage Tech',
    description: 'Intelligence gathering protocols.',
    baseCost: { metal: 200, crystal: 1000, deuterium: 200 },
    multiplier: 2.0,
    requirements: { research_lab: 3 },
  },
  computer_tech: {
    id: 'computer_tech',
    name: 'Computer Tech',
    description: 'Grants +1 fleet slot per level.',
    baseCost: { crystal: 400, deuterium: 600 },
    multiplier: 2.0,
    requirements: { research_lab: 1 },
  },
  astrophysics: {
    id: 'astrophysics',
    name: 'Astrophysics',
    description: 'Deep space exploration. Max Colonies = floor(Level/2) + 1.',
    baseCost: { metal: 4000, crystal: 8000, deuterium: 4000 },
    multiplier: 2.0,
    requirements: { research_lab: 3, espionage_tech: 4, impulse_drive: 3 }
  },
  intergalactic_net: {
    id: 'intergalactic_net',
    name: 'Intergalactic Research Network',
    description: 'Links research labs across planets for unified research.',
    baseCost: { metal: 240000, crystal: 400000, deuterium: 160000 },
    multiplier: 2.0,
    requirements: { research_lab: 10, computer_tech: 8, hyperspace_tech: 8 }
  },
  graviton_tech: {
    id: 'graviton_tech',
    name: 'Graviton Tech',
    description: 'Requires 300,000 Energy to complete.',
    baseCost: { energy: 300000 },
    multiplier: 3.0,
    requirements: { research_lab: 12 }
  },
  weapon_tech: {
    id: 'weapon_tech',
    name: 'Weapons Technology',
    description: 'Enhances attack strength of all units.',
    baseCost: { metal: 800, crystal: 200 },
    multiplier: 2.0,
    requirements: { research_lab: 4 }
  },
  shield_tech: {
    id: 'shield_tech',
    name: 'Shielding Tech',
    description: 'Energy-based defensive arrays.',
    baseCost: { metal: 200, crystal: 600 },
    multiplier: 2.0,
    requirements: { research_lab: 6, energy_tech: 3 }
  },
  armor_tech: {
    id: 'armor_tech',
    name: 'Armor Technology',
    description: 'Improves integrity of hulls and structures.',
    baseCost: { metal: 1000 },
    multiplier: 2.0,
    requirements: { research_lab: 2 }
  }
};

export const SHIPS: Record<string, Ship> = {
  small_cargo: {
    id: 'small_cargo',
    name: 'Small Cargo',
    description: 'Light transport vessel. Efficiency over power.',
    baseCost: { metal: 2000, crystal: 2000 },
    multiplier: 1.0,
    stats: { hull: 4000, shield: 10, attack: 5, speed: 5000, cargo: 5000 },
    rapidFire: { espionage_probe: 5, solar_satellite: 5 },
    requirements: { shipyard: 2, combustion_drive: 2 },
  },
  large_cargo: {
    id: 'large_cargo',
    name: 'Large Cargo',
    description: 'Heavy logistics backbone.',
    baseCost: { metal: 6000, crystal: 6000 },
    multiplier: 1.0,
    stats: { hull: 12000, shield: 25, attack: 5, speed: 7500, cargo: 25000 },
    rapidFire: { espionage_probe: 5, solar_satellite: 5 },
    requirements: { shipyard: 4, combustion_drive: 6 },
  },
  light_fighter: {
    id: 'light_fighter',
    name: 'Light Fighter',
    description: 'Basic interceptor.',
    baseCost: { metal: 3000, crystal: 1000 },
    multiplier: 1.0,
    stats: { hull: 4000, shield: 10, attack: 50, speed: 12500, cargo: 50 },
    rapidFire: { espionage_probe: 5, solar_satellite: 5 },
    requirements: { shipyard: 1, combustion_drive: 1 },
  },
  heavy_fighter: {
    id: 'heavy_fighter',
    name: 'Heavy Fighter',
    description: 'Uprooted and powerful.',
    baseCost: { metal: 6000, crystal: 4000 },
    multiplier: 1.0,
    stats: { hull: 10000, shield: 25, attack: 150, speed: 10000, cargo: 100 },
    rapidFire: { small_cargo: 3 },
    requirements: { shipyard: 4, armor_tech: 2, impulse_drive: 2 }
  },
  cruiser: {
    id: 'cruiser',
    name: 'Cruiser',
    description: 'Anti-fighter heavy interceptor.',
    baseCost: { metal: 20000, crystal: 7000, deuterium: 2000 },
    multiplier: 1.0,
    stats: { hull: 27000, shield: 50, attack: 400, speed: 15000, cargo: 800 },
    rapidFire: { light_fighter: 6, rocket_launcher: 10 },
    requirements: { shipyard: 5, impulse_drive: 4, ion_tech: 2 },
  },
  battleship: {
    id: 'battleship',
    name: 'Battleship',
    description: 'Heavy offensive fleet backbone.',
    baseCost: { metal: 45000, crystal: 15000 },
    multiplier: 1.0,
    stats: { hull: 60000, shield: 200, attack: 1000, speed: 10000, cargo: 1500 },
    rapidFire: { espionage_probe: 5 },
    requirements: { shipyard: 7, hyperspace_drive: 4 },
  },
  battlecruiser: {
    id: 'battlecruiser',
    name: 'Battlecruiser',
    description: 'Hunter of heavy vessels.',
    baseCost: { metal: 30000, crystal: 40000, deuterium: 15000 },
    multiplier: 1.0,
    stats: { hull: 70000, shield: 400, attack: 700, speed: 10000, cargo: 750 },
    rapidFire: { large_cargo: 5, battleship: 7, cruiser: 4 },
    requirements: { shipyard: 8, hyperspace_tech: 5, hyperspace_drive: 5, laser_tech: 12 }
  },
  bomber: {
    id: 'bomber',
    name: 'Bomber',
    description: 'Precision strikes against defenses.',
    baseCost: { metal: 50000, crystal: 25000, deuterium: 15000 },
    multiplier: 1.0,
    stats: { hull: 75000, shield: 500, attack: 1000, speed: 4000, cargo: 500 },
    rapidFire: { rocket_launcher: 20, light_laser: 20 },
    requirements: { shipyard: 8, impulse_drive: 6, plasma_tech: 5 }
  },
  destroyer: {
    id: 'destroyer',
    name: 'Destroyer',
    description: 'Shield-breaker and capital ship killer.',
    baseCost: { metal: 60000, crystal: 50000, deuterium: 15000 },
    multiplier: 1.0,
    stats: { hull: 110000, shield: 500, attack: 2000, speed: 5000, cargo: 2000 },
    rapidFire: { battlecruiser: 2, light_laser: 10 },
    requirements: { shipyard: 9, hyperspace_tech: 5, hyperspace_drive: 6 }
  },
  deathstar: {
    id: 'deathstar',
    name: 'Deathstar',
    description: 'The ultimate weapon. Moon-killer.',
    baseCost: { metal: 5000000, crystal: 4000000, deuterium: 1000000 },
    multiplier: 1.0,
    stats: { hull: 9000000, shield: 50000, attack: 200000, speed: 100, cargo: 1000000 },
    rapidFire: { light_fighter: 200, cruiser: 33, battleship: 30, rocket_launcher: 200 },
    requirements: { shipyard: 12, hyperspace_tech: 6, hyperspace_drive: 7, graviton_tech: 1 },
  },
  pathfinder: {
    id: 'pathfinder',
    name: 'Pathfinder',
    description: 'Deep space expedition vessel.',
    baseCost: { metal: 8000, crystal: 15000, deuterium: 8000 },
    multiplier: 1.0,
    stats: { hull: 23000, shield: 100, attack: 200, speed: 12000, cargo: 10000 },
    rapidFire: { light_fighter: 3 },
    requirements: { shipyard: 5, hyperspace_drive: 2, shield_tech: 4 },
  },
  recycler: {
    id: 'recycler',
    name: 'Recycler',
    description: 'Harvester of orbital debris.',
    baseCost: { metal: 10000, crystal: 6000, deuterium: 2000 },
    multiplier: 1.0,
    stats: { hull: 16000, shield: 10, attack: 1, speed: 2000, cargo: 20000 },
    rapidFire: { espionage_probe: 5 },
    requirements: { shipyard: 4, combustion_drive: 6, shield_tech: 2 }
  },
  colony_ship: {
    id: 'colony_ship',
    name: 'Colony Ship',
    description: 'Used to expand your empire. Disassembles upon landing to form a base.',
    baseCost: { metal: 10000, crystal: 20000, deuterium: 10000 },
    multiplier: 1.0,
    stats: { hull: 30000, shield: 100, attack: 50, speed: 2500, cargo: 10000 },
    rapidFire: {},
    requirements: { shipyard: 4, impulse_drive: 3 },
  },
  espionage_probe: {
    id: 'espionage_probe',
    name: 'Espionage Probe',
    description: 'Small, fast scouting drone.',
    baseCost: { crystal: 1000 },
    multiplier: 1.0,
    stats: { hull: 1000, shield: 1, attack: 1, speed: 100000000, cargo: 5 },
    rapidFire: {},
    requirements: { shipyard: 3, espionage_tech: 3 },
  },
  solar_satellite: {
    id: 'solar_satellite',
    name: 'Solar Satellite',
    description: 'Orbiting power collectors.',
    baseCost: { crystal: 2000, deuterium: 500 },
    multiplier: 1.0,
    stats: { hull: 2000, shield: 1, attack: 1 },
    rapidFire: {},
    requirements: { shipyard: 1 },
  }
};

export const DEFENSE: Record<string, Ship> = {
  rocket_launcher: {
    id: 'rocket_launcher',
    name: 'Rocket Launcher',
    description: 'Basic kinetic planetary defense.',
    baseCost: { metal: 2000 },
    multiplier: 1.0,
    stats: { hull: 2000, shield: 20, attack: 80 },
    rapidFire: {},
    requirements: { shipyard: 1 },
  },
  light_laser: {
    id: 'light_laser',
    name: 'Light Laser',
    description: 'Reliable photon-based defense.',
    baseCost: { metal: 1500, crystal: 500 },
    multiplier: 1.0,
    stats: { hull: 2000, shield: 25, attack: 100 },
    rapidFire: {},
    requirements: { shipyard: 2, laser_tech: 3 },
  },
  plasma_turret: {
    id: 'plasma_turret',
    name: 'Plasma Turret',
    description: 'Ultimate planetary defense unit.',
    baseCost: { metal: 50000, crystal: 50000, deuterium: 30000 },
    multiplier: 1.0,
    stats: { hull: 100000, shield: 300, attack: 3000 },
    rapidFire: {},
    requirements: { shipyard: 8, plasma_tech: 7 },
  }
};
